### ISSUE TITLE
Add getting started manual

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#10]
Add getting started manual:

- Get buildings data from OpenstreetMap;
- Import buildings in PostGIS;
- Process buildings (triangulate, project);
- Run tiling pg2b3dm;
- View results in Cesium.

**Comment by bertt** [comment]
for getting started see https://github.com/Geodan/pg2b3dm/blob/master/README.md#getting-started

**Comment by ali322** [comment]
how to process buildings(triangulate, project)?
