### ISSUE TITLE
Define the color for geometries visualization

### ISSUE THREAD

**Issue by IoannaTsakalakidou** [Geodan/pg2b3dm#100]
I want to assign different color to each of my geometries based on a specific value of an attribute. Which flag should I use to set the geometry color, and what data type should I give (i.e. json or string of hex color)?

- I used the flag `--default_color` to set a fixed color value but no change was applied. 
- In the example in `getting_started.md` the colors are given as input in the `tesselate_building` tool but I am not using this tool to triangulate my geometries.

**Comment by bertt** [comment]
Hi, 

- about default_color: you can add --default_color #FF0000 (and remove the --shaderscolumn option), all geometries will be red;

- if you want a specific shader for each triangle use  --shaderscolumn option. See https://github.com/Geodan/pg2b3dm#shaders for more information about this

**Comment by bertt** [comment]
alternative option is to use the styling in the Cesium client https://github.com/CesiumGS/3d-tiles/tree/main/specification/Styling

**Comment by IoannaTsakalakidou** [comment]
> 

Hi Bert, 

Is it possible to give the color value from a column in the table? I want my geometries to have a certain color based on criteria from another column. When I tried adding a column with colors, I got the following error: 

>  Unhandled exception. System.ArgumentException: <my_color_column> is not a valid value for Int32. (Parameter 'htmlColor')

The column is of type string with hex color values.

**Comment by bertt** [comment]
no there is at the moment --default_color  (1 color for all triangles) or --shaderscolumn  (1 shader for each triangle). 

Maybe your case is more suitable for styling based on attribute in the Cesium client, something like:

```
   var buildings = new Cesium.Cesium3DTileset({
        url : './buildings/tileset.json'
    });

    buildings.style = new Cesium.Cesium3DTileStyle({
      color: {
        conditions: [
        ["${feature['bouwjaar']} <= 1700", "color('#430719')"],
        ["${feature['bouwjaar']} > 1700", "color('#740320')"],
        ]
      }
    }
  );
```

**Comment by IoannaTsakalakidou** [comment]
> 

Thank you @bertt for the alternative. I adjusted your solution to my case and it's not working since all the features are colored the same. I believe that what is going wrong in my case is that it doesn't find the attribute in the conditions field. 

To make sure I understand correctly, let's call the desired attribute `bouwjaar`. This attribute is found in a postgres table which is used as an input in pg2b3dm, right? My question is how is the attribute `bouwjaar` becoming available through the reference `url : './buildings/tileset.json'`? Are the columns of the postgres table passing to the .b3dm outputs?

**Comment by bertt** [comment]
when running pg2b3dm you've to add '-a bouwjaar' (bouwjaar must be a column in the input table)

**Comment by IoannaTsakalakidou** [comment]
It works with the column name in the -a flag. Thanks!
