### ISSUE TITLE
Why did the installation report an error

### ISSUE THREAD

**Issue by ShareQiu1994** [Geodan/pg2b3dm#102]
![image](https://github.com/Geodan/pg2b3dm/assets/19948086/a04b8571-7b4f-4e13-9014-df866489c5c1)

**Comment by bertt** [comment]
can you try with:

```
$ dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources pg2b3dm
```

**Comment by ShareQiu1994** [comment]
I'll try Docker's solution

**Comment by bertt** [comment]
strange can you see https://api.nuget.org/v3/index.json ?

**Comment by ShareQiu1994** [comment]
yean , I can

**Comment by bertt** [comment]
ok, does this work?

![image](https://github.com/Geodan/pg2b3dm/assets/538812/73951366-ff29-4df0-9493-8e16db055b13)

**Comment by ShareQiu1994** [comment]
![image](https://github.com/Geodan/pg2b3dm/assets/19948086/c34d1e06-24b8-42e0-a8ef-e9ad3a8aae7c)
Em, my computer output is like this
