### ISSUE TITLE
Converting ArcGIS multipatch in PostGIS to b3dm

### ISSUE THREAD

**Issue by ashitoshp** [Geodan/pg2b3dm#113]
Hello,
Does this also support ArcGIS multipatch GDB geometries in PostGIS as an input?

**Comment by bertt** [comment]
Interesting option to investigate, it should work when the geometry is stored as MultiPolygonZ in epsg 4978. In DBeaver it should look like:
 
![image](https://github.com/Geodan/pg2b3dm/assets/538812/ba5a29f1-f981-4487-b565-8e64e75c0ced)

I can imagine an extra view/column in the database is needed to create the correct input geometries
