### ISSUE TITLE
tileset.json not generated, only b3dm

### ISSUE THREAD

**Issue by aleksmelnyk** [Geodan/pg2b3dm#116]
Hi there,

I have tried to convert triangulation to cesium, as a result having only set of *.b3dm files, no .subtree or tileset.jsonn available. No matter if I use --use_implicit_tiling in both cases it is same.
Did I miss something?

thanks much.

**Comment by aleksmelnyk** [comment]
Ok, in order to enabled cesium mode, geometries must be in 4978 srid. By default it is in experimental mapbox3 mode, which doesn't generate the mentioned files.

**Comment by bertt** [comment]
yeah mode is selected based on spatial reference of input table (3857-> MapBox, 4978 -> Cesium)
