### ISSUE TITLE
3D tiles render above terrain and under grid

### ISSUE THREAD

**Issue by iskandari** [Geodan/pg2b3dm#128]
Thank you for providing this very useful tool!  

I started with regular 2D polygons that represent shallow areas of the ocean (no Z component), and followed the tutorial with Delaware buildings, assigning an arbitrary height of 100 to my polygons. 

```sql
SELECT 
ogc_fid, height, ST_GeometryType(geom_triangle)
FROM shallows_3d LIMIT 5;

79	100	"ST_PolyhedralSurface"
595	100	"ST_PolyhedralSurface"
78	100	"ST_PolyhedralSurface"
898	100	"ST_PolyhedralSurface"
89	100	"ST_PolyhedralSurface"
```

After converting to 3D tiles, I am curious as to why the polygons seem to float above the terrain (as opposed to being extruded to this height) and at the same time, I am confused as to why both the 3D tiles and Cesium World Terrain appear below the grid in Unity (note: this is with default settings).  Is this expected?  If so, could you advise on generating 3D tiles that sit on the grid?  

<img width="942" alt="Screenshot 2023-11-23 at 9 06 51 PM" src="https://github.com/Geodan/pg2b3dm/assets/8308461/a0489758-5772-4773-8e8c-d8cd631e1427">

**Comment by bertt** [comment]
Hi, thanks

- in the first case all the vertices have z=100? In the getting started https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md there is a step 'tesselate_building' that creates vertices with Z=0 (footprint) and Z=100 (roof).

- In CesiumJS the world terrain  is by default disabled, in Cesium it's enabled. To get the buildings on a correct altitude relative to the terrain, the terrain height is for each building is needed in the process. So this is a bit more complicated.

**Comment by bertt** [comment]
Hi thanks,

I think in both cases you've got the terrain enabled?

If so, the terrain height is defined relative to the ellipsoid. It's a bit complicated to get the 3D Tiles also on a correct height relative to the terrain, the terrain height for each building is needed. See blog https://bertt.wordpress.com/2023/07/11/adding-objects-to-google-photorealistic-3d-tiles/ for some more details.
