### ISSUE TITLE
2.x.x: deck.gl does not draw tiles

### ISSUE THREAD

**Issue by skemaikin** [Geodan/pg2b3dm#137]
Hi,

Tiles generated by versions `2.x.x `(starting from version 2.0.0, 4978 -> 4326) are not drawn by the `deck.gl` library. They are loaded, but not drawn.  
Tiles are prepared with `use_implicit_tiling=false`. The `asset.version` inside the `teleset.json` was manually changed to `1.0` (the tileset follows this format).

Thanks!

**Comment by bertt** [comment]
Hi did you try with 2.1 also?

**Comment by bertt** [comment]
ok, is there a minimal Deck.gl client to reproduce this? Maybe also a sample when it was working.

**Comment by skemaikin** [comment]
> ok, is there a minimal Deck.gl client to reproduce this? Maybe also a sample when it was working.

[deckgl-viewer.zip](https://github.com/Geodan/pg2b3dm/files/14042628/deckgl-viewer.zip)
Tileset hosted on `localhost:3000/tileset.json`     You can change this url (`app.js:90`).  Nodejs v.18.18.2.

**Comment by bertt** [comment]
Something to check: If the client only support 1.0 (so only .b3dm files) you have to use ' --create_gltf false' also (otherwise glb's are created)

**Comment by skemaikin** [comment]
> Something to check: If the client only support 1.0 (so only .b3dm files) you have to use ' --create_gltf false' also (otherwise glb's are created)

Yes, I did so. `... --create_gltf false --use_implicit_tiling false`

**Comment by bertt** [comment]
Fixed it in https://github.com/Geodan/pg2b3dm/commit/fb80c4f577179951bc8ec560cf4c61d3085e7b79

You can also change in tileset.json the transform the last 0 to 1:

From

```
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      1238318.875,
      -4794808.5,
      4006101.5,
      0.0
```

To

```
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      1238318.875,
      -4794808.5,
      4006101.5,
      1.0
```

**Comment by skemaikin** [comment]
> Fixed it in [fb80c4f](https://github.com/Geodan/pg2b3dm/commit/fb80c4f577179951bc8ec560cf4c61d3085e7b79)

Now it works fine!!! 

Another wish: It seems to me that while using the parameters `--create_gltf false --use_implicit_tiling false` the version can be defined as `1.0`.  Of course as per your preferences )))

**Comment by bertt** [comment]
Great it works :-) 

I shall look into the version 1.0 when --create_gltf false --use_implicit_tiling false for next release

**Comment by bertt** [comment]
PR for setting 1.0 version see https://github.com/Geodan/pg2b3dm/pull/138

**Comment by bertt** [comment]
2.2 is released with these fixes
