### ISSUE TITLE
Short linestrings not rendered?

### ISSUE THREAD

**Issue by stevenjh** [Geodan/pg2b3dm#161]
I'm successfully running this against a table of LINESTRING Z to generate pipe networks, I am getting outputs.

But I've got an issue where short records are not being created in the output tiles, see this screenshot of the 3d tiles rendered and the associated linestrings on top
![image](https://github.com/Geodan/pg2b3dm/assets/1258872/77c90a35-ab74-4f6a-bed6-4110f0454856)

I'm trying to follow the code through to where this might be happening but haven't got to the bottom of it, wondering if it's something about screen space errors and any help would be appreciated!

Thanks,
Steven

**Comment by bertt** [comment]
Hi, maybe some lines are there but under the terrain? To debug you can use a high number for --max_features_per_tile and inspect the created glb in a glTF viewer

**Comment by stevenjh** [comment]
Thanks for the reply and suggestions, viewing the glb directly I can see it's only picking up the two pipes as rendered in the screenshot from qgis above. This was also filtered down to only be the 9 features pictured above, the WKT geometry on the features looks fine too.
Thanks again, I'm on vacation for a week but will pick up my troubleshooting on my return.

**Comment by bertt** [comment]
ok if you have a wkt of a not rendered line I can take a look

**Comment by stevenjh** [comment]
I've messaged you in twitter for email, and also ended up pasting in the insert statements of the features pictured above.

**Comment by bertt** [comment]
non repro? 
![image](https://github.com/Geodan/pg2b3dm/assets/538812/4fc0da2c-fa32-4cf3-b5d5-65b98abb566d)

**Comment by stevenjh** [comment]
I was working against version 2.6, your comment in twitter about a resolved bug of 'two vertice lines failing to render' was correct, moving to the latest release resolved the issues. Thanks!
