### ISSUE TITLE
Issue about not rendering Delaware polygons into Unity

### ISSUE THREAD

**Issue by Mitko88** [Geodan/pg2b3dm#168]
I've followed the steps as suggested, but I get an error in Unity. What could go wrong?

[2024-05-30 17:25:56.823] [error] [ErrorList.h:72] Errors when loading tileset:
- Error when parsing tileset JSON, error code 3 at byte offset 0

The error is not very specific, that is why I've shared a link to the generated tiles:
https://drive.google.com/drive/folders/1CZDuQw-ls5z2f9yXD6flSZH1gOFJn1NR?usp=sharing

**Comment by Mitko88** [comment]
Thank you for the quick reply. I've used these two parameters.

pg2b3dm -h localhost -U postgres -c geom_triangle -t delaware_buildings -d postgres -a ogc_fid --shaderscolumn shaders --create_gltf false --use_implicit_tiling false
Tool: pg2b3dm 2.8.1.0
Options: -h localhost -U postgres -c geom_triangle -t delaware_buildings -d postgres -a ogc_fid --shaderscolumn shaders --create_gltf false --use_implicit_tiling false
Password for user postgres:
Start processing 2024-05-30T19:56:23....
Input table: delaware_buildings
Input geometry column: geom_triangle
App mode: Cesium
Spatial reference of delaware_buildings.geom_triangle: 4326
Spatial index detected on delaware_buildings.geom_triangle
Query bounding box of delaware_buildings.geom_triangle...
Bounding box for delaware_buildings.geom_triangle (in WGS84): -75.59158711, 39.08939264, -75.44656349, 39.23050979
Height values: [0 m - 76.58 m]
Default color: #FFFFFF
Default metallic roughness: #008000
Doublesided: True
Create glTF tiles: False
Attribute columns: ogc_fid
Center (wgs84): -75.51907530249994, 39.15995121350005
Starting Cesium mode...
Translation ECEF: 1238318.875,-4794808.5,4006101.5
3D Tiles version: 1.0
Lod column:
Radius column:
Geometric errors: 2000,0
Refinement: REPLACE
Add outlines: False
Use 3D Tiles 1.1 implicit tiling: False
Maximum features per tile: 1000
Start generating tiles...
Creating tile: 4_11_8.b3dm
Tiles created: 238
Geometric errors used: 2000,0
Writing tileset.json files...
Writing tileset_3_5_4.json...
External tileset.json files: 27
Writing root tileset.json...

Time: 0h 0m 22s 916ms
Program finished 2024-05-30T19:56:46.

I've tried to visualize the tiles in Cesium ion, and I do not see any polygon.

**Comment by bertt** [comment]
looks alright like this, should be able to visualize the results in CesiumJS/Cesium for Unity. I'll take a look later

**Comment by bertt** [comment]
tried it, works alright for me... One difference I see it's:

Tiles created: 60

versus:

Tiles created: 238

**Comment by Mitko88** [comment]
I've figured out what is the issue. I did not configure the server properly to call the tileset.json. I've visualized the tiles properly in Unity now.

Thank you for the help!
