### ISSUE TITLE
Option --shaderscolumn deprecated

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#173]
Notice: Option --shaderscolumn is deprecated and will be removed in a upcoming release (breaking change)

With option shaderscolumn it's possible to define the shader per triangle in the database, using a predefined JSON format.
See https://github.com/Geodan/pg2b3dm/blob/master/styling.md

Although a very powerful mechanism, reasons for deprecation are:

- function is not used much;

- function is complex and slows down new developments;

- function does not work when triangulation is performed by pg2b3dm (for example with lines or non triangulated geometries)

Alternative  options are:

- Set styling options for the complete tileset --default_color, --default_metallic_roughness;

- Use client side styling, see https://github.com/Geodan/pg2b3dm/blob/master/styling.md#client-side-styling.

**Comment by bertt** [comment]
PR see https://github.com/Geodan/pg2b3dm/pull/172

**Comment by mittermichal** [comment]
hello do I understand correctly that this PR will break usage of tesselate_building that sets shaders column?
so it is planned that tesselate_building with pg2b3dm will create buildings with uniform color?

my use case can't use client-style styling because the output is intended for Cesium for Unreal which doesn't support that yet https://github.com/CesiumGS/cesium-unreal/issues/1392

**Comment by bertt** [comment]
yeah it's a breaking change with result uniform styled geometries, good to you know you are using this feature. This change might need some reconsideration.
Are you using different styling for building roofs and walls?

**Comment by mittermichal** [comment]
I don't have any particular data, but I was told by superior that its wanted feature and I already made REST API that wraps this conversion that can color features by attribute mapping, attribute intervals and interval to color interpolation, and configuration can be different for roof, wall and floor. I will ask them to participate in this conversation.

I think it would be better if it was possible to style it on client side, but it's just not supported in cesium for unreal.

**Comment by mittermichal** [comment]
what is geometry in this context? a polygon?

**Comment by bertt** [comment]
yes one of the input geometry types  LineStrings/Polygon/MultiPolygon/PolyhedralSurface/TIN

Input table in this case will look like:

| Geometry  | Shader                                               |
| --------- | ---------------------------------------------------- |
| polygon1  | `{'PbrMetallicRoughness': {'BaseColor': ['#008000']}}` |
| polygon2  | `{'PbrMetallicRoughness': {'BaseColor': ['#00FFFF']}}` |

Will this work for you?

**Comment by mittermichal** [comment]
yes, thank you

**Comment by bertt** [comment]
@ivopisarovic I'm thinking if the above solution is in place (with 1 style per geometry) to rewrite the  tesselate_building tool a bit, so for each building there will be 3 geometries in the table (for roof, walls, floor) with an extra attribute for the type. The style can then be set in the style column. 
Would that work for you?

Note it will take some time to implement these changes so for now the current solution will still work.

**Comment by ivopisarovic** [comment]
@bertt Sure, it would be awesome! :) No problem it will take time. We can help with testing later if you need.

**Comment by mittermichal** [comment]
do I understand correctly that the order of geometry in geometry collection corresponds to order in shadercolumn BaseColors list?
