### ISSUE TITLE
Please allow password/connection string to be specified

### ISSUE THREAD

**Issue by sebastianmattar** [Geodan/pg2b3dm#175]
Hi!

Thanks a lot for pg2b3dm - we use this tool to generate 3d tiles for Cesium.
To move the tile generation into a pipeline and make it run in batch mode, we need to be able to provide a password to connect to the database. The current implementation relies on trusted connections or using an interactive prompt.
We can not use trusted connections as it is not secure enough in a k8s environment. It would be great if we could get a way to provide the password by using an environment variable.

Thank you! :)

**Comment by bertt** [comment]
Ok, I'll take a look into that, I see others are using 'PGPASSWORD' environment variable would that be ok?

**Comment by sebastianmattar** [comment]
Thank you for the swift answer, will try!
