### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ZsoltMONOLITE** [Geodan/pg2b3dm#197]
Hi,

Let me have a question, i wonder is the created glTF cound be used in an AR settings as well?

Thank you

**Comment by bertt** [comment]
Hi, yes if the AR supports glTF 2.0 ... What AR are you using?

From Cesium there are toolkits for Unity3D and Unreal, they can be used to build AR apps.

You can also build something yourself, maybe most easy is to use the --format Mapbox option in pg2b3dm then glTF's according to the XYZ tiling schema are created.
