### ISSUE TITLE
Impossible to create 3D tiles if value are set to NULL

### ISSUE THREAD

**Issue by plaulhe** [Geodan/pg2b3dm#216]
Hello, how are you since last time?  :)

I am currently using the pg2b3dm tool with my datasets, and I've encountered an issue where certain fields contain only NULL values. This is causing a problem during type determination, as indicated by the following error message:

sql
Copier le code
2024-10-17 11:48:36,838 - ERROR - Unhandled exception. System.Exception: All values of attribute 'hauteur' are Null, can't determine type.
Unfortunately, I cannot modify the values by replacing NULL with another value.

Is there a solution to handle this situation within pg2b3dm? Any guidance or workaround would be greatly appreciated.

Thank you for your assistance!

Best regards,

**Comment by bertt** [comment]
Hi, yes I've noticed this too, as a workaround you can add '--create_gltf  false' (so b3dm files instead of glb), or omit the hauteur attribute.

**Comment by bertt** [comment]
https://github.com/Geodan/pg2b3dm/pull/217

**Comment by bertt** [comment]
fixed in release 2.18.1
