### ISSUE TITLE
Colors not correctly assigned

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#24]
This is the real colors in the dataset:
![image](https://user-images.githubusercontent.com/1998463/62955432-5574d980-bdf1-11e9-8185-834079f3c849.png)

But this is when viewing the output in Cesium:
![image](https://user-images.githubusercontent.com/1998463/62955502-76d5c580-bdf1-11e9-8087-686fd878d9df.png)

**Comment by bertt** [comment]
should be fixed in 0.4.2 (https://github.com/Geodan/pg2b3dm/commit/f991c8ee7f0121adedbb18332060def5b11d0ca7)
