### ISSUE TITLE
Colors on wall instead of roof

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#25]
Since version 0.4.4.0 it seems that the roofcolor is assigned to SE facing walls only.

![image](https://user-images.githubusercontent.com/1998463/63221930-cf65e380-c1a0-11e9-8d58-7429063f1fb8.png)
(color shows almost black on picture)

**Comment by bertt** [comment]
in release 0.5, colors  per triangle can be specified in the database
