### ISSUE TITLE
Commandline parameters renaming

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#27]
Commandline parameters renaming proposal:

1] Geometry column
From:
-c, --column          (Default: geom) Geometry column name
To:
-g -geometrycolumn (Default: geom) Geometry column name

2] Color column
From:
 -r , --roofcolorcolumn (default: '') color column name
To:
 -c , -colorcolumn (default: '') color column name

**Comment by tomvantilburg** [comment]
`-c` is used in pgsql client for giving a querystring. This may be an interesting future feature so perhaps keep the `-c` available for adding a custom query?  Perhaps capital C would be better?

**Comment by bertt** [comment]
in 0.10 the -r , --roofcolorcolumn option is removed so closing this issue
