### ISSUE TITLE
Optimize queries/database connection

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#32]
Currently the speed of pg2b3dm seems to be depending on the queries to the database. It seems some queries may be optimized or may benifit from indexes.

**Comment by bertt** [comment]
sql used for retrieving geometries tile 1.b3dm (input table  -h metis.geodan.nl -d maquette_nl -c geom -t  results.extruded_4978 -r color -p 5433)

```
select row_number, ST_AsBinary(geom1), color from(SELECT row_number() over(), geom1 , color FROM(select ST_RotateX(ST_Translate(geom, 3888187.1491730586*-1,334536.70548817236*-1 , 5028080.295359469*-1), -pi() / 2) as geom1, ST_Area(ST_Force2D(geom)) AS weight , color FROM results.extruded_4978 where ST_GeometryType(geom) =  'ST_PolyhedralSurface' ORDER BY weight DESC) as t) as p where row_number in (5,33,39,41,49,144,287,315,317,348,358,368,369,405,423,434,461,468,487,512,514,559,588,608,610,646,652,684,689,697,734,752,753,773,774,795,805,867,870,879,905,914,944,992,1002,1003,1017,1020,1021,1043)
```

**Comment by tomvantilburg** [comment]
This query takes >5 secs, which seems a lot for only 50 records.
I don't understand the working of the query though. On what is the selection of row_numbers based?

**Comment by bertt** [comment]
these are the 50 largest buildings in the dataset (determined in an earlier step).

Alternative option: use mandatory id field instead of row_number?

**Comment by tomvantilburg** [comment]
This might be a faster way of getting the geometries once you have the identiefiers from query 2:
```
SELECT
	blockid,
	ST_AsBinary(ST_RotateX(ST_Translate(geom, 3888187.1491730586*-1,334536.70548817236*-1 , 5028080.295359469*-1), -pi() / 2)) geom,
	color 
FROM results.extruded_4978 
WHERE ST_GeometryType(geom) =  'ST_PolyhedralSurface' 
AND blockid IN ('list','with','nblockids')
```

**Comment by tomvantilburg** [comment]
That was an easy fix:
```
CREATE INDEX ON results.extruded_4978 USING btree(blockid);
```
Now down to 700 ms

**Comment by bertt** [comment]
fixed in https://github.com/Geodan/pg2b3dm/commit/e14cd94778e41574c66cabc38db032458f2d752a , release 0.7

Don't forget to add option -i blockid and index column blockid
