### ISSUE TITLE
Dark tiles

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#37]
When inspecting subsurface demo https://geodan.github.io/pg2b3dm/sample_data/index_geotop.html some parts of tiles are rendered completely dark:

<img width="1147" alt="Screenshot 2020-02-26 at 11 48 03" src="https://user-images.githubusercontent.com/538812/75337865-1d654d80-588e-11ea-8abd-44ff1006baa3.png">

**Comment by bertt** [comment]
Trying to reproduce

Step 1] Unpack b3dm to gltf

$ ~/.dotnet/tools/b3dm unpack 9.b3dm

gltf/glb files for GeoTop demo are added see https://github.com/Geodan/pg2b3dm/commit/6499b10e58f269722ec73b01cf869d31b5d17ba9

2] Visualize in Visual Studio Code with Babylon.js/Cesium/Three.js:

<img width="1253" alt="Screenshot 2020-02-26 at 12 27 57" src="https://user-images.githubusercontent.com/538812/75341428-b303db80-5894-11ea-88da-01f7ae6a88bb.png">

Conclusion: no dark walls visible. Must be something in MapBox viewer?

**Comment by bertt** [comment]
@B-de-V Can we close this one? I think it's solved by using other shader/lighting.

**Comment by B-de-V** [comment]
Yes, I think we can.
