### ISSUE TITLE
Rotated tiles

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#38]
At the moment the tiles are rotated:

![cesium_rotated](https://user-images.githubusercontent.com/538812/75769488-8cd3b500-5d46-11ea-839b-184926ef4762.png)

Q: Is it possible to generate and visualize tiles without the rotation, like:

![cesium_not_rotated](https://user-images.githubusercontent.com/538812/75769526-9fe68500-5d46-11ea-8a91-23a86085bec1.png)

**Comment by tomvantilburg** [comment]
If this is the cesium viewer, the thing that is rotated is the surface of the earth, not the tiles since they just follow the earth centered coordinate space.

**Comment by bertt** [comment]
Maybe we can use boundingVolume.region (instead of boundingVolume.box), where tile location is defined  as  [west, south, east, north, minimum height, maximum height] in WGS84.

**Comment by bertt** [comment]
wont fix
