### ISSUE TITLE
Tiles generated but not in correct location

### ISSUE THREAD

**Issue by hkalbertl** [Geodan/pg2b3dm#39]
Hi, I followed the "Getting started" section and used Delaware data to start with.
No problems occurred during conversion and I can get tileset.json and list of b3dm files.

After that, I modified the sample_data/index_cesium.html file to use the above tileset but the buildings were floating in space. 

I noticed that the projection need to be 4978 as mentioned in #35. I recreated database table by using 4978 projection but I still cannot get the building displayed in Delaware.
Here is a screenshot during loading the Cesium viewer, I can see some buildings there but they are in somewhere around South America.
![cesium](https://user-images.githubusercontent.com/4110287/75955225-5d60ac00-5ef0-11ea-8c00-355f6fabcbfb.jpg)

This is the tileset json in Chrome development tool.
![tileset](https://user-images.githubusercontent.com/4110287/75955370-ac0e4600-5ef0-11ea-94be-32b50d4fd0dd.jpg)

And here are some details of my development machine:
Windows 10 Pro
Docker Desktop 2.2.0.3
GDAL 2.4.3 (for ogr2ogr)

Can anyone give me some advice? Thank you!

**Comment by bertt** [comment]
Something goes wrong with the z values in case of Cesium. I'll try to fix it.

**Comment by bertt** [comment]
Got it working again see https://geodan.github.io/pg2b3dm/sample_data/delaware/cesium/

The process bertt/tesselate_building has now a new  -f --format option, possible values cesium/mapbox, defaults to 'mapbox'.

You can pull a new docker images by: $ docker pull bertt/tesselate_building

The getting_started document is also partly rewritten. 

Some known issues with Cesium:

- When using the terrain option the buildings are above the ground;

- The colors are a bit funky, don't see the red somehow.

**Comment by hkalbertl** [comment]
![image](https://user-images.githubusercontent.com/4110287/76060754-f65cf900-5fbc-11ea-8117-d2dec5033487.png)

The new version of tesselate_building works fine.
And I can visualize my own data now.
Thank you!
