### ISSUE TITLE
Make command line parameters like psql

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#4]

**Comment by bertt** [comment]
Fixed in https://github.com/Geodan/pg2b3dm/commit/93d04734f052e4d2b2e3563842827ee44d811a0a

**Comment by tomvantilburg** [comment]
Password should be optional. Currently it always asks for password, even when no password is needed because connection is trusted.

**Comment by bertt** [comment]
fixed by https://github.com/Geodan/pg2b3dm/commit/4d60c13d911ffabe82acf90e59df3fe22c98d307
