### ISSUE TITLE
Default extent maybe too large

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#42]
Turns out that the tiles with a default extent of 2000 meters will grow up to 20 MB in size.
When setting it to 250 meters tiles tend not to exceed 2mb and mostly stick to around 700 k

**Comment by bertt** [comment]
Ok what default extent shall we use? 1000? Alternative is to use the lod system.

**Comment by bertt** [comment]
default extenttile is now set to 1000 https://github.com/Geodan/pg2b3dm/commit/da545dccada15e978d4d7a681d86873df3e0ff4f
