### ISSUE TITLE
Max-Z of every tile seems to be set to max-Z of whole dataset

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#43]
This causes all tiles to be very large, especially when there's an error in the data, and consequently this gives unexpected results when taking the geometricError into account.
Didn't check but Min-Z has likely the same behaviour but less important.

**Comment by bertt** [comment]
Yes at the moment the minZ and maxZ are calculated for the whole dataset and applied to each tile. The was done for performance reasons. Alternative is to calculate minZ and maxZ for each tile but the tool will get a bit slower.

**Comment by bertt** [comment]
won't fix, check errors in data before running
