### ISSUE TITLE
lod seems to assume to have 0

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#44]
Is see this query passing by on a dataset that has lod levels 1 and 2 but not 0:
```
select exists(
	select geom 
	from results.extruded_3857_dst 
	where ST_Intersects(ST_Centroid(ST_Envelope(geom)), ST_MakeEnvelope(467395.56335918076, 6765013.961907677, 467895.56335918076, 6765513.961907677, 3857)) 
	and ST_GeometryType(geom) =  'ST_PolyhedralSurface' 
	and lod=0
)
```

The result is that *no* features are being exported since obviously no feature has lod=0

Is this seems to by not intentional since pg2b3dm first correctly finds the lod levels present as:
`Detected 2 lod levels: [1,2]`

**Comment by bertt** [comment]
fixed in https://github.com/Geodan/pg2b3dm/commit/53fb20725f112ad7f87ad5de8caf6a8f0a59f0d7
