### ISSUE TITLE
'refinement' parameter is implemented as 'refine'

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#47]
```
ERROR(S):
  Option 'refinement' is unknown.
```

So docs and commit message need to be changed ;-)

**Comment by bertt** [comment]
I shortened it from 'refinement' to 'refine'. Where in the docs 'refinement' is used?

**Comment by tomvantilburg** [comment]
Not anymore since you changed it ;-)
Got it from this commit: 
https://github.com/Geodan/pg2b3dm/commit/bc2cc084ab22cce402a154afefe848122d0b4521
