### ISSUE TITLE
Enable specular and emissive color as well

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#49]
Currently only diffusecolor is set for the materials.
Having the option to add specular and emissive color on top of diffuse color would greatly enhance the visuals. Most BIM models do have a combination of the three.

**Comment by tomvantilburg** [comment]
Add ambientcolor and shinyness to the list...

**Comment by bertt** [comment]
these options are specified in Materials.KnownChannel enumeration, available options:

Normal, Occlusion, Emissive, BaseColor, MetallicRoughness, Diffuse, SpecularGlossiness, ClearCoat, ClearCoatNormal, ClearCoatRoughness

At the moment only BaseColor is used.

**Comment by tomvantilburg** [comment]
Might make sense to provide a JSON from the database with the material information? Gives us more flexibility then keep adding columns.

**Comment by bertt** [comment]
In the current glTF's the default pbrMetallicRoughness shader is used for BaseColor, AlphaMode aand DoubleSided. Possible other options are: MetallicFactor (default 1) and RoughnessFactor (default 1).

There is an glTF extension called 'pbrSpecularGLossiness' shader (see https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness) where things like DiffuseColor, SpecularColor, GlossinessFactor can be defined. 

One option is to support pbrSpecularGLossiness shaders as an optional capability in pg2b3dm.

Q: Does mapbox-3dtiles/three.js support glTF's with pbrSpecularGLossiness shaders?

**Comment by bertt** [comment]
Proposal JSON structure:

```
{
    "emissiveColors": [list_of_colors in hex [R,G,B,-]]
    "pbrMetallicRoughness": {
        "baseColors": [ list_of_colors in hex [R, G, B, Alpha]],
        "metallicRoughness": [list_of_metallic_roughness in hex [Metallic Factor, Roughness Factor, -, -]]
    },
    "extensions": {
        "pbrSpecularGlossiness": {
            "diffuseColors": [list_of_colors in hex [R, G, B, Alpha]],
            "specularGlosiness": [ list_of_colors in hex [R, G, B, Glossiness]],
        }
    }
}
```

When both SpecularGlossiness and MetallicRoughness are specified, the glTF fallback scenario can be used (for clients with no support for SpecularGlossiness)

**Comment by tomvantilburg** [comment]
Not sure if I understand the array-in-array for the list of colors with both hex and separate RGBA. Can you give an example?

**Comment by bertt** [comment]
Ok, sample for record with 2 triangles:

```
{
    "extensions": {
        "pbrSpecularGlossiness": {
            "diffuseColors": ["#E6008000","#E6008000"],
            "specularGlosiness": ["#4D0000ff", "4D0000ff"]
        }
    }
}
```

Explanation:

diffuseColor #E6008000 means RGB color = #008000 (0,128,0) with alpha = E6 (85%) 
specularGlossiness #4D0000ff means specular Color RGB = #0000ff (0,0,255) with glossiness = 4D (25%)

Model is derived from https://github.com/vpenades/SharpGLTF/tree/master/src/SharpGLTF.Toolkit/Materials so I hope it should be easy to implement.

**Comment by tomvantilburg** [comment]
OK, arrays of hexbin colors seem fine to me. 

Is the "extensions" object really needed for the JSON that is used as input to pg2b3dm? I understand that it mimics the way the gltfs uses a separate extension for the _KHR_materials_pbrSpecularGlossiness_ but to me it seems to add confusion since there is no extension on that part of the pipeline.

**Comment by bertt** [comment]
yeah I'll remove the 'extensions' object

**Comment by bertt** [comment]
for first preview of this functionality see https://github.com/Geodan/pg2b3dm/blob/shaders/src/release_notes_0.10.md

**Comment by bertt** [comment]
this shaders functionality is now in master branch and release 0.10, closing issue

**Comment by tomvantilburg** [comment]
THREE has introduced a change in v121 that breaks the coloring of pbrSpecularGlossiness:
https://github.com/mrdoob/three.js/pull/20226/files

When I change those lines in the GLTFLoader manually the color is as it is expected so it's for sure that change. I cant't wrap my head around where it actually goes wrong though.

**Comment by bertt** [comment]
Here a  sample with SpecularGlossiness: Specular RGB = 50, 60, 70 Glossiness =80
[specularglossiness.zip](https://github.com/Geodan/pg2b3dm/files/9291078/specularglossiness.zip)
