### ISSUE TITLE
Add option of adding a query instead of tablename

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#50]
The tool would become more flexible if one would be able to write a query with for instance some subselect right away in the command instead of creating a table in the database first.

**Comment by bertt** [comment]
why not create a view?

**Comment by tomvantilburg** [comment]
Currently that is the way I'm doing it but it has some disadvantages:
1) needs a separate connection and interface to the database
2) I may not have the rights to create a view or table
3) the view may already exist and in the worst case overridden in the process
4) I should remember to delete the view after use (which I obviously won't)

**Comment by bertt** [comment]
See branch https://github.com/Geodan/pg2b3dm/tree/add_query_parameter

This is for simple queries like -q "ogc_fid=118768"

Is this sufficient? @B-de-V

**Comment by B-de-V** [comment]
@bertt That is already nice, but is it perhaps possible to make query option like: -sql "SELECT a.id,  a.diffuse as color, a.geom FROM table a WHERE ST_Intersects(a.geom, some_extent)"

**Comment by bertt** [comment]
hmm no, that would require a major refactor I'm afraid

**Comment by bertt** [comment]
Note: The query parameter -q handles only a SQL 'where' part. 

Working sample for spatial query:

-q "ST_Intersects(wkb_geometry, 'SRID=4326;POLYGON((-75.56996406 39.207228824,-75.56996406 39.2074420320001,-75.5696300339999 39.2074420320001,-75.5696300339999 39.207228824,-75.56996406 39.207228824))'::geometry)"

**Comment by B-de-V** [comment]
Nice! Saves a lot of time and space creating the separate tables.

**Comment by bertt** [comment]
Docker image for testing this functionality: geodan/pg2b3dm:0.9.3-with_query

**Comment by tomvantilburg** [comment]
Tested and works great! 
Remark for the docs: make sure you create an index on the table when it is getting big.

**Comment by bertt** [comment]
added in https://github.com/Geodan/pg2b3dm/pull/52 release 0.9.4
