### ISSUE TITLE
Alpha channel and colors

### ISSUE THREAD

**Issue by AleMScof** [Geodan/pg2b3dm#54]
Hi all,
i am having some trouble trying to get working b3dm tiles along with alpha channel.

Following the docs alpha channel is meant to be working.
if i set the style column as 

`'{ "walls": "#A6D92400", "roof":"#A67D2900", "floor":"#A6D75200"}'`

i am expecting to have those colors 60% transparent.

Any clue to what am i doing wrong?

Thanks,
A.

**Comment by bertt** [comment]
Hi, I've tried it also for color red (255,0,0), results:

95% - almost opaque
"walls": "#F2ff0000", "roof":"#F2ff0000", "floor":"#F2ff0000"

![image](https://user-images.githubusercontent.com/538812/97473903-cbf4ed00-194b-11eb-950c-474580c1d87e.png)

5% - almost transparent
"walls": "#0Dff0000", "roof":"#0Dff0000", "floor":"#0Dff0000"

![image](https://user-images.githubusercontent.com/538812/97473998-e7f88e80-194b-11eb-8776-92aecd9cf6fd.png)

In glTF 2.0 terms KnownChannel.BaseColor is set with the color and AlphaMode.OPAQUE is used. 

Maybe you are looking for some other glTF effect?

**Comment by bertt** [comment]
Some more investigation: AlphaMode.OPAQUE means the output is fully opaque and any alpha value is ignored. So I've changed the AlphaMode to BLEND (https://github.com/Geodan/pg2b3dm/commit/b4352de1f5a894bd8c548e452b863570f0540148). The 5% - "walls": "#0Dff0000", "roof":"#0Dff0000", "floor":"#0Dff0000" now looks as follows:

![image](https://user-images.githubusercontent.com/538812/97500567-1d16d800-1970-11eb-8341-6a23cc9b36ac.png)

To test you can pull latest Docker image with: $ docker pull geodan/pg2b3dm:latest

**Comment by AleMScof** [comment]
Great,

i gave it a try and it's working as i was expecting earlier.

`UPDATE mytablename SET style = ('{ "walls": "#A6D92400", "roof":"#A67D2900", "floor":"#A6F75200"}');
`
Results here: 

![Schermata del 2020-10-29 13 25 16](https://user-images.githubusercontent.com/29773796/97580545-be933d80-19f3-11eb-806a-5381291c13e0.jpeg)

Much appreciated,
issue can be closed.
A.

**Comment by bertt** [comment]
great!

**Comment by bertt** [comment]
whats the red thing i'm seeing?

**Comment by AleMScof** [comment]
> whats the red thing i'm seeing?

Hi bertt,
if you mean the extruded polygon that's a no-fly zone
