### ISSUE TITLE
--attributescolumn not working

### ISSUE THREAD

**Issue by simayguzel** [Geodan/pg2b3dm#56]
I am trying to use the --attributescolumn parameter but I get this error:

Here is my command line:

`docker run -v $(pwd)/output:/app/output -it geodan/pg2b3dm -h xxx -U xxx -c geom_triangle  -t sos.uv_sb -d xxx -i id --attributescolumn ogc_fid --shaderscolumn shaders `
The error: 
![error1](https://user-images.githubusercontent.com/44606954/106604055-64a89380-655f-11eb-91e2-7ec1dabd26d2.png)
![error2](https://user-images.githubusercontent.com/44606954/106604371-d680dd00-655f-11eb-8d34-c8b0726dda52.png)

PostgreSQL doesn't have exactly a data type ‘String’ but text, varchar, etc… So I don’t know how I could add an attributes column.

**Comment by bertt** [comment]
it must be a string array type column, text[]

**Comment by simayguzel** [comment]
Thank you!

**Comment by enersis-pst** [comment]
i coudnt see id and any props on hover. Only batchId: 0 is inside of feature properties.
I use the amsterdam js example with my 3d-tiles.

`docker run -it --network mynetwork -v ${PWD}/output14:/app/output geodan/pg2b3dm -h some-postgis -U postgres -c geom -t lod22 -d postgres -i id -a props --shaderscolumn shaders`

in db:
id is text = myfirstBilding
props is text[] = {breakfast,consulting}

For me its also not clear how the string array should be to show property and value inside of the feature properties.

**Comment by bertt** [comment]
the command looks good at first sight (including the -a props). The resulting b3dm(s) file should contain the batch table with the values from the props column. 
One method to check the b3dm batch table is to install https://github.com/bertt/b3dm.tooling . Command $ b3dm info -i your_tile.b3dm prints the batch table among others.

**Comment by enersis-pst** [comment]
```
b3dm info -i .\output14\tiles\1.b3dm
Action: Info
b3dm file: .\output14\tiles\1.b3dm
b3dm header version: 1
b3dm header magic: b3dm
b3dm header bytelength: 2620
b3dm header featuretablejson length: 20
b3dm header batchtablejson length: 24
Feature table json: '{"BATCH_LENGTH":1}  '
Batch table json: '{"props":["breakfast"]} '
Validation check: no errors
glTF model is loaded
glTF generator: SharpGLTF 1.0.0-alpha0018
glTF version:2.0
glTF primitives: 1
glTF triangles: 16
Bounding box vertices: -12,62159, 12,62159, -5,916, 5,916, -9,450581, 9,450581
Primitive 0 (TRIANGLES) batch ids (unique): 0
glTF extensions used: KHR_materials_pbrSpecularGlossiness
glTF: no extensions required.
```

so it only have first, but it isnt there if i hover it. Also no id. Can i take any string for id? And how properties should be stored to have key,value?

**Comment by bertt** [comment]
ok, so tile .\output14\tiles\1.b3dm contains one building with attribute props="breakfast". You should check the client Javascript code to see how the batch table json per b3dm tile is handled.

Note 1:  the id is not used in the attributes table;
Note 2: batch table support was added in a late stage, there are some proposals to add support for multiple attributes per feature and improve client side support.

**Comment by enersis-pst** [comment]
@bertt thanks.
i will check the attributes in js.
But what about the id? can i also check if it inside the b3dm? and should it then also be at feature.id?

**Comment by bertt** [comment]
the id is only used internally in pg2b3dm, if you want to show it up it the client you'll have to put it in the attributes column.

**Comment by enersis-pst** [comment]
i took the newest Mapbox3DTiles.js from dist, comment the line 
`this.outlinePass.selectedObjects = [intersect.object];`
now the attribte is visible :-)
