### ISSUE TITLE
Tiles generated but not in correct location

### ISSUE THREAD

**Issue by learnerandtrainer** [Geodan/pg2b3dm#58]
Hi , I have been downloaded source code and change options according to my own database. when I run source code , it generated json and tiles but when I want to showing them on the map by cesium, cesium read all documents but it cant show them on map.  Can anyone give me some advice? Thank you!
My coordinate referans : 5255

here is results
Cessium
![image](https://user-images.githubusercontent.com/66632022/108321206-e42b9900-71d4-11eb-978f-b1bc0dcf5177.png)
Network
![image](https://user-images.githubusercontent.com/66632022/108321342-13daa100-71d5-11eb-8d09-273f1585d7f8.png)

Some wkt examples (The exact position of geometries is turkey)
"POLYGON Z ((488951.848009659 4425041.66991106 873.450722531613,488940.657246581 4425046.98496842 873.450722531613,488949.182685909 4425064.93513627 873.450722531613,488960.373448987 4425059.62007892 873.450722531613,488951.848009659 4425041.66991106 873.450722531613))"

"POLYGON Z ((488951.848009659 4425041.66991106 889.109484574175,488960.373448987 4425059.62007892 889.109484574175,488949.182685909 4425064.93513627 889.109484574175,488940.657246581 4425046.98496842 889.109484574175,488951.848009659 4425041.66991106 889.109484574175))"

"POLYGON Z ((488951.848009659 4425041.66991106 873.450722531613,488951.848009659 4425041.66991106 889.109484574175,488940.657246581 4425046.98496842 889.109484574175,488940.657246581 4425046.98496842 873.450722531613,488951.848009659 4425041.66991106 873.450722531613))"

"POLYGON Z ((488945.586434 4425057.351567 889.109484,488947.918969 4425053.908233 889.109484,488944.681064 4425055.44924 889.109484,488945.586434 4425057.351567 889.109484))"

**Comment by bertt** [comment]
input data must be epsg:4978 for Cesium

**Comment by learnerandtrainer** [comment]
Thank you for quick response. I will try it
