### ISSUE TITLE
How can I convert polygon that is not triangle

### ISSUE THREAD

**Issue by learnerandtrainer** [Geodan/pg2b3dm#59]
Hi,
I tested source code on data that has epsg:4978 and it was work finely , But my types of geometry are non-triangular geometries.
How can I use rectangular geometries , Can you give me any advise? Can I use polygon?

Preview of current situation
![image](https://user-images.githubusercontent.com/66632022/108469717-d429bd00-7299-11eb-8575-6e4d2776ba5d.png)

Some wkt examples (The exact position of geometries is turkey)
"POLYGON Z ((488951.848009659 4425041.66991106 873.450722531613,488940.657246581 4425046.98496842 873.450722531613,488949.182685909 4425064.93513627 873.450722531613,488960.373448987 4425059.62007892 873.450722531613,488951.848009659 4425041.66991106 873.450722531613))"

"POLYGON Z ((488951.848009659 4425041.66991106 889.109484574175,488960.373448987 4425059.62007892 889.109484574175,488949.182685909 4425064.93513627 889.109484574175,488940.657246581 4425046.98496842 889.109484574175,488951.848009659 4425041.66991106 889.109484574175))"

"POLYGON Z ((488951.848009659 4425041.66991106 873.450722531613,488951.848009659 4425041.66991106 889.109484574175,488940.657246581 4425046.98496842 889.109484574175,488940.657246581 4425046.98496842 873.450722531613,488951.848009659 4425041.66991106 873.450722531613))"

"POLYGON Z ((488945.586434 4425057.351567 889.109484,488947.918969 4425053.908233 889.109484,488944.681064 4425055.44924 889.109484,488945.586434 4425057.351567 889.109484))"

**Comment by bertt** [comment]
The input geometries must be triangulated. You can follow the getting started document https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md
