### ISSUE TITLE
Question: How to do generalization?

### ISSUE THREAD

**Issue by enersis-pst** [Geodan/pg2b3dm#62]
I saw this example, where buildings poppin in and out depending on the zoom level and position. 
Could someone please explain how this is possible by this converter?
https://geodan.github.io/pg2b3dm/sample_data/duisburg/mapbox/#16.28/51.435087/6.789592/0/45

**Comment by enersis-pst** [comment]
nevermind find this
https://github.com/Geodan/pg2b3dm/blob/master/src/release_notes_0.9.md

**Comment by bertt** [comment]
Yeah although a nice effect we removed it because a bit confusing to see only part of the buildings (the larger features)

**Comment by enersis-pst** [comment]
please leave it. I think for a higher lever this make sense.
