### ISSUE TITLE
Tiles dissappear when Word Terrain is picked as terrain

### ISSUE THREAD

**Issue by KlemenSpruk** [Geodan/pg2b3dm#63]
Hi! 

I have converted 3D polygons(Z = ellipsoid elevation) from postgres with postgis db  to 3D tiles.
On Cesium Web UI view when WGS84 ellipsoid is picked, display is ok. But when Word Terrain is picked, tilles disappear, they probably go underground. How to take ellipsoid height into account to get right display when World Terrain is used?

Is it possible to pass ellipsoid height that determines height above terrain for object?

**Comment by bertt** [comment]
can you try with depthTestAgainstTerrain = true ?

**Comment by KlemenSpruk** [comment]
Hi!

Tnx for response. This setting did not help. If I added ellipsoid height for polygon centroid to height attribute then display was ok. But this is a hack. Is it possible to define height above terrain and then extrude polygon with height attribute?

My UI code:

<script>
  var viewer = new Cesium.Viewer("cesiumContainer");
  viewer.scene.globe.depthTestAgainstTerrain = true;
  var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url: 'http://localhost:8000/tiles/3d/cesium/obstacles/config?authkey'
  }));

  tileset.style = new Cesium.Cesium3DTileStyle({
    color: {
      conditions: [
        ["true", "color('red', 0.5)"],
      ],
    },
  });

  tileset.readyPromise.then(function (tileset) {
    var boundingSphere = tileset.boundingSphere;
    viewer.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0, -2.0, 0));
    viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
  });
</script>

**Comment by bertt** [comment]
One option I'm thinking is changing the z-values in the tileset.json file (for example https://geodan.github.io/pg2b3dm/sample_data/delaware/cesium/tileset.json). This file defines the position of the tiles (x, y, z).

Another option is some customization in the Cesium client indeed.

**Comment by KlemenSpruk** [comment]
Tried the above option and it works but produces bad results. Elevations adjustment should be done per feature but many features can be on tile.
Could height above terrain be taken into account in source code? Like an extra column? Is such an option "compliant" with 
tiler tool design?

**Comment by bertt** [comment]
yes in the tileset.json the position of the tiles is defined, but a tile has multiple features (like buildings). A better approach is to define offsetZ column in the database (for the terrain heights), and use these values when generating the glTF models. 

Note: these models will look strange in viewers without terrain.

**Comment by KlemenSpruk** [comment]
Is offsetZ column an extra column besides default height column or is it just replacement for height column? If its just a replacement then polygons will be extruded for value but part of them will still be underground part of them will look out of the terrain. In such a case polygon bottom face will not be above terrain.

**Comment by bertt** [comment]
In this tool the geometry column contains 3D polyhedralsurface geometries (for example a building). One method is to add the terrain height to all vertice Z values of the geometry in the database. With this method no code change is required.

Another method is to add an offsetZ column (so no height column) and use this when generating the models.

**Comment by KlemenSpruk** [comment]
My input geometries are already with Z value:
![Screenshot 2021-04-14 at 11 49 49](https://user-images.githubusercontent.com/8971677/114691116-9f753780-9d17-11eb-9090-84e72ca6fdb5.png)

But I will remove it and try to add value in geom_triangle vertexes and see what happens. WiIl post the result. TNX!

**Comment by KlemenSpruk** [comment]
Hi! I tested the option with adding height to geom_triangle vertices. It works but then position of the feature on ground is a bit changed.
