### ISSUE TITLE
Error st_makeenvelope doesn't exist running pg2b3dm

### ISSUE THREAD

**Issue by dsoto74** [Geodan/pg2b3dm#74]
Hi.

I've tried follow "getting started" guide to test pg2b3dm.

In the last step "Run pg2b3dm", I'm getting the following error:
creating quadtree: 1/140 - 0,71%Unhandled exception. Npgsql.PostgresException (0x80004005): 42883: no existe la función st_makeenvelope(integer, bigint, integer, integer, integer, bigint, integer, integer, integer)

I've attached file with whole error message.

I'm testing it on Windows 10, PostgresSQL 14.1 and Postgis 3.2.

Any ideas to solve it?

Thanks.
Dani.
[pg2b3dm_st_makeenvelope error.txt](https://github.com/Geodan/pg2b3dm/files/7913599/pg2b3dm_st_makeenvelope.error.txt)

**Comment by bertt** [comment]
Hi see https://github.com/Geodan/pg2b3dm/issues/72
