### ISSUE TITLE
Capturing individual 3D objects from b3dm file

### ISSUE THREAD

**Issue by ayman-aljullaq** [Geodan/pg2b3dm#75]
Hello,

I have a batched 3D model in b3dm format containing 3D tiles (an example -> [batched.zip](https://github.com/Geodan/pg2b3dm/files/8929576/batched.zip)) and I’m looking for tools that can help to get the geometry data of each individual object. I need this geometry data to calculate the volume of these individual objects.

I would like to ask you:

if it is possible to capture the geometry data of each 3D object.
If there is a tool/library/framework that helps to extract these geometries.
I’ve already done a lot of research to find a tool that can help, but couldn’t find one.

I would be very grateful for your help.

Thanks in advance

**Comment by bertt** [comment]
Hi, it looks like there is something wrong with batched.b3dm, 3D Tiles Validator (https://github.com/CesiumGS/3d-tiles-validator/tree/main/validator) gives:

```
Header is using the legacy format [batchLength] [batchTableByteLength]. The new format is [featureTableJsonByteLength] [featureTableBinaryByteLength] [batchTableJsonByteLength] [batchTableBinaryByteLength].
```

How did you create this file? 

Inside the b3dm file there is a glTF, individual objects are identified by the custom vertex attribute _BATCHID. To calculate the volumes of individual objects it would require to select the vertices per _BATCHID, construct a 3D object from it, and calculate the volumes. I don't think there is tooling to perform this, but it shouldn't be difficult to code.

If you have access to the original data, maybe a better approach is to calculate the volumes from that dataset.
