### ISSUE TITLE
Tiles appear to decrease geometricError from top-left to bottom-right

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#8]
This becomes noticable when running a large dataset. The top-left corner will still show small geometries wheras on the bottom-right only the very large geometries are shown.

**Comment by tomvantilburg** [comment]
Turns out this is happens when the program stops halfway because of invalid geometries. Because the tiling starts from top-left it gives this effect. Will open a new issue on error-handling for this.

**Comment by bertt** [comment]
error handling issue see https://github.com/Geodan/pg2b3dm/issues/9
