### ISSUE TITLE
roof does not display in ue5

### ISSUE THREAD

**Issue by martin416** [Geodan/pg2b3dm#86]
The generated 3dtiles data is displayed normally in cesium. js:
![image](https://user-images.githubusercontent.com/8612796/212011089-3c4027cc-92e4-4c06-8f6a-7a5434b5e767.png)

but the roof is not displayed in cesium for ue5.
cesium for unreal engine5,version1.18
![image](https://user-images.githubusercontent.com/8612796/212011484-eb9aeed2-5044-428f-84ba-15c26fc4f8cb.png)

and how to set style like osmbuilding?

**Comment by martin416** [comment]
[3dtiles-output2.zip](https://github.com/Geodan/pg2b3dm/files/10407360/3dtiles-output2.zip)

**Comment by bertt** [comment]
looks the same like https://github.com/Geodan/pg2b3dm/issues/114, something with doubleSided/triangles orientation

**Comment by bertt** [comment]
I've created a new version of tool tesselate_building (0.2.2) can you try again?
