### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#9]
Add error handling for:

- Invalid geometries;
- Geometries that are not trianguled.

Q: should process completely stop when detecting invalid/not triangulated geometries or just ignore them and continue?

Proposal: Just stop the process   when detecting invalid/not triangulated geometries with correct error message.

**Comment by tomvantilburg** [comment]
Would be nice to be able to set the option of 'stop on error' but to let it continue by default. My guess is that most of the time these are geometries that shouldn't have been there anyway

**Comment by bertt** [comment]
no need adding more error handling now
