### ISSUE TITLE
tile creation fails

### ISSUE THREAD

**Issue by QSafariallahkheili** [Geodan/pg2b3dm#94]
I am trying to create tiles for building dataset with triangulated geometries (using tesselate_building tool) following the steps and dataset in tutorial. However, afeter running pg2b3dm and providing the table specifications I get the following error:

```
pg2b3dm -h localhost -U berlinberlin -c geom_triangle -t delaware_buildings -d brandenburg -a id,height --shaderscolumn shaders
```

**Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.** (below screenshot)

<img width="1440" alt="Screenshot 2023-05-19 at 09 47 10" src="https://github.com/Geodan/pg2b3dm/assets/50631096/2978f8cf-3d28-4805-a74b-3b247ea2f78f">

I am using  pg2b3dm 1.5.3.0, Tesselate buildings 0.2.0.0, PostGIS 3.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

I would appreciate any response or possible solution.

**Comment by bertt** [comment]
Hi, your geometries are in '3857' (for MapBox) but should be in '4978' for Cesium

```
Spatial reference of delaware_buildings.geom_triangle: 4978
```

Did you run tesselate_building as stated in the getting started (including -f cesium)?

```
$ tesselate_building -h localhost -U postgres -d postgres -f cesium -t delaware_buildings -i wkb_geometry -o geom_triangle --idcolumn ogc_fid --stylecolumn style --shaderscolumn shaders
```

**Comment by bertt** [comment]
@GinaStavropoulou we stopped supporting MapBox, it may still work with older versions of pg2b3dm

**Comment by GinaStavropoulou** [comment]
Thank you! I will be using just cesium then!

**Comment by QSafariallahkheili** [comment]
@bertt Thanks for your response.

I am using Maplibre GL JS with DeckGL. I tried to tesselate building with ```-f cesium``` then create tiles with ```pg2b3dm 0.16.0.0``` as the deckgl fails to render tiles with implicit tiling. However it does render the tiles but the rendering performance is very poor as the deckgl tries to call b3dms outside of the area of interest (focus area).

however I created mapbox tile (EPSG:3857) and tried to render the tile with ```@geodanresearch/mapbox-3dtiles``` package but it fails because of dependency conflict or no vivid reason. Do you have any recommendation on how can I mapbox tile in my existing Maplibre application?

**Comment by bertt** [comment]
@QSafariallahkheili as stated above, you can try to use pg2b3dm version < 1.0 for MapBox, maybe it works with @geodanresearch/mapbox-3dtiles
