### ISSUE TITLE
Cannot connect to db

### ISSUE THREAD

**Issue by sehHeiden** [Geodan/pg2b3dm#96]
I want to use Polygons for planned buildings with Cesium.

Therefore I did the following prepararing.
1. computed the estimated height over ground
2. forced the z-coordinate to the new height over ground
3. fixed
4. I am not sure, whether the polygons have to be extruded?
5. I used qgis to tesselate the polygons... :(( Which created errors for some buildings.
6. saved as geojson
7. created a new postgres table
8. added the objects via ogr2ogr
9. installed the docker container

I started pg2b3dm with the Command on windows: 

>  docker run -v D:\path\to\output:/app/output -it geodan/pg2b3dm -h localhost -U username -d dbname -t tablename -c wkb_geometry

I tried localhost and 127.0.0.1 as host.
For localhost I got the following callback:

> Tool: pg2b3dm 1.5.3.0
> Password for user postgres:
> Start processing 2023-06-06T13:00:09....
> Input table: tablename
> Input geometry column: wkb_geometry
> Lod column:
> Geometric errors: 2000,0
> Geometric error used for implicit tiling: 2000
> Unhandled exception. Npgsql.NpgsqlException (0x80004005): Failed to connect to [::1]:5432
>  ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (99): Cannot assign requested address [::1]:5432
>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
>    at Npgsql.Internal.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
>    at Npgsql.Internal.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
>    at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
>    at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|214_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
>    at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
>    at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
>    at Npgsql.PoolingDataSource.<Get>g__RentAsync|28_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
>    at Npgsql.NpgsqlConnection.Open()
>    at B3dm.Tileset.DatabaseReader.ReadScalar(IDbConnection conn, String sql) in /src/b3dm.tileset/DatabaseReader.cs:line 9
>    at B3dm.Tileset.SpatialReferenceRepository.GetSpatialReference(IDbConnection conn, String geometry_table, String geometry_column) in /src/b3dm.tileset/SpatialReferenceRepository.cs:line 10
>    at pg2b3dm.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in /src/pg2b3dm/Program.cs:line 100
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at pg2b3dm.Program.Main(String[] args) in /src/pg2b3dm/Program.cs:line 28

with 127.0.0.1 its the same error but for a IPv4 address.

I assume I can not properly connect? Is it a password/typo  error possible or does it have to a real connection error?
I checked and connected the table to Pycharm and  to a Pythonscript:

```python
    db_connection_url = "postgresql://postgres:password$@localhost:5432/dbname"
    engine = create_engine(db_connection_url)
    sql = "SELECT * FROM tablename"
    gdf= GeoDataFrame.from_postgis(text(sql), engine.connect(), geom_col='wkb_geometry', crs=4987)
```

Its very similar. Hence, I cannot really believe in a connection error or a typo.

**Comment by bertt** [comment]
Hi, looks like something with the Db connection indeed. Can you do the getting started https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md it might give some clues.

**Comment by sehHeiden** [comment]
Thanks, that getting started page is very detailed. It could be featured more prominently.

Still I got some problems while installing the tools with  ```dotnet tools install ...```.

For both pg2b3dm/tesselate_buildings (https://github.com/bertt/tesselate_building/issues/3).

Because I have the same problem with installing both tools I loked for general problems with `dotnet tool install`.
I tried: https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues

What worked is: dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources tesselate_building.

On the main Readme.md docker is featured prominently, but not in the getting started. Could docker be added there, too?

**Comment by bertt** [comment]
Ok great it's working. There was a version with Docker commands once, I switched it to dotnet tools because Docker gave issues with some people... A promising step is to switch to AOT deployment to get rid of the dependencies.

**Comment by sehHeiden** [comment]
A tiny thing. I just figured out that wgs84 is mendatory not for the tesselation but for pg2b3dm. I assume that is not documented.

**Comment by sehHeiden** [comment]
The example Delaware was in epsg:4326 conversion of the table worked.

My Buildings are in epsg:253833, conversion in pg2b3dm did not work.
```bash
Bounding box for dachhoehe_pg2b3dm.geom_triangle (in WGS84): 8, 8, 8, 8
Heights for bounding volume: [0 m, 100 m]
Add outlines: False
Default color: #FFFFFF
Default metallic roughness: #008000
Translation: NaN,NaN,NaN
Attribute columns: id,height
Maximum features per tile: 1000
Start generating tiles...
Unhandled exception. Npgsql.PostgresException (0x80004005): 42703: Spalte »infinity« existiert nicht
```
I reprojected my geojson to epsg:4326 and than conversion went through.

**Comment by bertt** [comment]
ah yes tool tesselate_buildings needs geometries in epsg:4326 and creates geometries in epsg:4978 (to be used as input in pg2b3dm).
