### ISSUE TITLE
Tileset is not shown a masterportal instance

### ISSUE THREAD

**Issue by sehHeiden** [Geodan/pg2b3dm#97]
Yesterday I converted a vector file to ta a tileset. 

We want to use the tileset on a masterportal website. We included the output folder and opened the 3d view on the website.
But the b3dm filed did not load, when we were in the corresponding region of the 3d map. But the 0_0_0.subtree file has been loaded.

Is there any way to debug the problem?

<details>
<summary> The converted tileset is: </summary>

<code>

{
  "geometricError": 2000.0,
  "root": {
    "transform": [
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      3793975.5,
      878891.125,
      5034196.5,
      1.0
    ],
    "geometricError": 2000.0,
    "refine": "ADD",
    "boundingVolume": {
      "region": [
        0.22744155864620635,
        0.9154957723528067,
        0.22783664222114836,
        0.9157255774408974,
        0.0,
        100.0
      ]
    },
    "content": {
      "uri": "content/{level}_{x}_{y}.b3dm"
    },
    "implicitTiling": {
      "availableLevels": 2,
      "subdivisionScheme": "QUADTREE",
      "subtreeLevels": 1,
      "subtrees": {
        "uri": "subtrees/{level}_{x}_{y}.subtree"
      }
    }
  },
  "asset": {
    "generator": "pg2b3dm 1.5.3.0",
    "version": "1.0"
  }
}

</code>
</details>

The area should be north of Potsdam, Germany.

Edit: The file names for the b3dm files are: 1_0_0.b3dm, 1_0_1.b3dm, 1_1_0.b3dm, 1_1_1.b3dm
The subtree file is called: 0_0_0.subtree. I am wondering why the levels are different.

**Comment by bertt** [comment]
can you try with --use_implicit_tiling false ? and attach the 0_0_0.subtree file

**Comment by bertt** [comment]
Found it: 

There is a bug when using implicit tiling and only 4 tiles on level 1 are generated.

Workarounds:

- Use --use_implicit_tiling false

or 

- with implicit tiling true (that's the default) lower the --max_features_per_tile number (default 1000) so more levels are generated 

This issue will be fixed in a new release
