### ISSUE TITLE
Feature Request: Adapted Heights

### ISSUE THREAD

**Issue by sehHeiden** [Geodan/pg2b3dm#99]
I want politly ask for the following features that are related to height

- costumn ground elevation column: So that the building is only extruded to the ground, or building parts are able to have floors above the ground
- tesselation/extrudtion form z_Axis, instead of column. Some of the polygons I use are LoD2 roofs (with costumn z-axis), others are normal polygons (z-axis) is currently set to 0. But I might prefer to set the hight as z-Cooridinate instead of columns. Als it overs more details
- Is it possible to set different floors, perhaps as a building on another (which would allow different colors per floor).

**Comment by bertt** [comment]
I think this request belongs to https://github.com/bertt/tesselate_building. Pg2b3dm is a generic tool that processes a set of PolyhedralSurface geometries to 3D Tiles.
